spring:
  application:
    name: AutoCare-Service
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREE
    username: AUTOCAR
    password: autocar123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always                # ✅ LUÔN CHẠY KHI START APP
      continue-on-error: true    # ✅ KHÔNG DIE KHI TRÙNG DỮ LIỆU
      platform: oracle
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 6868
  address: 0.0.0.0
  servlet:
    context-path: /api

jwt:
  secret: qD9JxK2r7M8zP4uT1bV6yL3cN9eH5wR2fG8aS0dX7
  expiration: 864000000000
  refresh:
    expiration: 6048000000000

logging:
  level:
    com:
      health: INFO
  file:
    name: logs/autocare.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      access: unrestricted
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  metrics:
    tags:
      application: autocare-backend-api
