MERGE INTO BRANCH t
USING (
    SELECT 'Trụ sở chính' AS BRANCH_NAME, 'CN-TSC-000' AS BRANCH_CODE, '123 Lê trọng tấn, Tân phú, TP HCM' AS ADDRESS FROM dual UNION ALL
    SELECT 'Gò Vấp'     AS BRANCH_NAME, 'CN-GV-001' AS BRANCH_CODE, '123 Quang Trung, Gò Vấp, TP HCM' AS ADDRESS FROM dual UNION ALL
    SELECT 'Tân Bình'   AS BRANCH_NAME, 'CN-TB-002' AS BRANCH_CODE, '456 Cộng Hòa, Tân Bình, TP HCM'  AS ADDRESS FROM dual UNION ALL
    SELECT 'Bình Thạnh' AS BRANCH_NAME, 'CN-BT-003' AS BRANCH_CODE, '789 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP HCM' AS ADDRESS FROM dual UNION ALL
    SELECT 'Thủ Đức'    AS BRANCH_NAME, 'CN-TD-004' AS BRANCH_CODE, '12 Võ Văn Ngân, Thủ Đức, TP HCM' AS ADDRESS FROM dual UNION ALL
    SELECT 'Quận 7'     AS BRANCH_NAME, 'CN-Q7-005' AS BRANCH_CODE, '99 Nguyễn Thị Thập, Quận 7, TP HCM' AS ADDRESS FROM dual
) src
ON (t.BRANCH_CODE = src.BRANCH_CODE)
WHEN NOT MATCHED THEN
INSERT (BRANCH_NAME, BRANCH_CODE, ADDRESS, ACTIVE, CREATED_AT, UPDATED_AT)
    VALUES
    (src.BRANCH_NAME, src.BRANCH_CODE, src.ADDRESS, 1, SYSDATE, SYSDATE);

MERGE INTO AUTOCAR.APP_USER t
USING (
    SELECT
        1 AS ACTIVE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS CREATED_AT,
        'admin@gmail.com' AS EMAIL,
        'ADMIN' AS FULL_NAME,
        0 AS NEED_CREATE_PROFILE,
        '$2a$12$doBuwJ869fC8Vc1Qi3dPY.KWgNhNHI0aNzmSVvJefJ4DtkpcX2FwW' AS PASSWORD_HASH,
        'ADMIN' AS ROLE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS UPDATED_AT,
        'admin' AS USERNAME,
        1 AS BRANCH_ID
    FROM dual
    UNION ALL
    SELECT
        1 AS ACTIVE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS CREATED_AT,
        'duc@gmail.com' AS EMAIL,
        'Quản lý Đức' AS FULL_NAME,
        0 AS NEED_CREATE_PROFILE,
        '$2a$12$doBuwJ869fC8Vc1Qi3dPY.KWgNhNHI0aNzmSVvJefJ4DtkpcX2FwW' AS PASSWORD_HASH,
        'MANAGER' AS ROLE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS UPDATED_AT,
        'duc01' AS USERNAME,
        2 AS BRANCH_ID
    FROM dual
    UNION ALL
    SELECT
        1 AS ACTIVE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS CREATED_AT,
        'dang@gmail.com' AS EMAIL,
        'Quản lý Đăng' AS FULL_NAME,
        0 AS NEED_CREATE_PROFILE,
        '$2a$12$doBuwJ869fC8Vc1Qi3dPY.KWgNhNHI0aNzmSVvJefJ4DtkpcX2FwW' AS PASSWORD_HASH,
        'MANAGER' AS ROLE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS UPDATED_AT,
        'dang01' AS USERNAME,
        3 AS BRANCH_ID
    FROM dual
    UNION ALL
    SELECT
        1 AS ACTIVE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS CREATED_AT,
        'hao@gmail.com' AS EMAIL,
        'Hao' AS FULL_NAME,
        0 AS NEED_CREATE_PROFILE,
        '$2a$12$doBuwJ869fC8Vc1Qi3dPY.KWgNhNHI0aNzmSVvJefJ4DtkpcX2FwW' AS PASSWORD_HASH,
        'STAFF' AS ROLE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS UPDATED_AT,
        'hao23' AS USERNAME,
        2 AS BRANCH_ID
    FROM dual
    UNION ALL
    SELECT
        1 AS ACTIVE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS CREATED_AT,
        'huy@gmail.com' AS EMAIL,
        'Huy' AS FULL_NAME,
        0 AS NEED_CREATE_PROFILE,
        '$2a$12$doBuwJ869fC8Vc1Qi3dPY.KWgNhNHI0aNzmSVvJefJ4DtkpcX2FwW' AS PASSWORD_HASH,
        'STAFF' AS ROLE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS UPDATED_AT,
        'huy23' AS USERNAME,
        3 AS BRANCH_ID
    FROM dual
    UNION ALL
    SELECT
        1 AS ACTIVE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS CREATED_AT,
        'phat@gmail.com' AS EMAIL,
        'Phat' AS FULL_NAME,
        0 AS NEED_CREATE_PROFILE,
        '$2a$12$doBuwJ869fC8Vc1Qi3dPY.KWgNhNHI0aNzmSVvJefJ4DtkpcX2FwW' AS PASSWORD_HASH,
        'STAFF' AS ROLE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS UPDATED_AT,
        'phat' AS USERNAME,
        4 AS BRANCH_ID
    FROM dual
    UNION ALL
    SELECT
        1 AS ACTIVE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS CREATED_AT,
        'phi@gmail.com' AS EMAIL,
        'Phi' AS FULL_NAME,
        0 AS NEED_CREATE_PROFILE,
        '$2a$12$doBuwJ869fC8Vc1Qi3dPY.KWgNhNHI0aNzmSVvJefJ4DtkpcX2FwW' AS PASSWORD_HASH,
        'STAFF' AS ROLE,
        TO_TIMESTAMP('2025-12-09 17:58:50.200891', 'SYYYY-MM-DD HH24:MI:SS:FF6') AS UPDATED_AT,
        'phi' AS USERNAME,
        5 AS BRANCH_ID
    FROM dual
) src
ON (t.USERNAME = src.USERNAME)
WHEN NOT MATCHED THEN
INSERT ( ACTIVE, CREATED_AT, EMAIL, FULL_NAME, NEED_CREATE_PROFILE,
    PASSWORD_HASH, ROLE, UPDATED_AT, USERNAME, BRANCH_ID)
    VALUES
( src.ACTIVE, src.CREATED_AT, src.EMAIL, src.FULL_NAME, src.NEED_CREATE_PROFILE,
    src.PASSWORD_HASH, src.ROLE, src.UPDATED_AT, src.USERNAME, src.BRANCH_ID);
